### ISSUE TITLE
0617还需要在doAction函数中修改remark的值为“是”

### ISSUE THREAD

**Issue by bysdyc** [X1a0He/GuangzhouUniversity#1]
也可以改成否（doge）

**Comment by bysdyc** [comment]
也可以改成否（doge）

**Comment by xyi007** [comment]
确认那一块好像提交有错误

**Comment by X1a0He** [comment]
May be fixed in [#bc9608](https://github.com/X1a0He/GuangzhouUniversity/commit/bc9608d3b9f7ca5b26d8bdbbec4ed829321e44e2)
