### ISSUE TITLE
比如设置了五点半的抢场，抢不到之后会随机选择另外时间段抢，代码需要做哪些修改才能使得固定退后一个时间段（比如三点半）进行抢呢

### ISSUE THREAD

**Issue by William-ZZh** [X1a0He/GuangzhouUniversity#3]
你好，我用你的脚本预约成功了很多回场，但有一个疑问就是比如我提前设置了抢5点半的场，但是抢不到之后它会随机选择另外的时间段进行抢，我需要对代码的哪个地方进行修改，才能使得抢不到五点半的场，它会往后退一个时间段，比如三点半的场，再开始继续抢呢

**Comment by X1a0He** [comment]
注: 时间与场地的优先级为 场地(X号场) > 时间，详细分为4种情况
1. 不指定场地不指定时间，则脚本会随机预约随机场地随机时间
2. 指定场地不指定时间，则脚本会优先预约同一个场地(X号场)的所有时间，若不成功，则进入随机预约
3. 指定场地指定时间，则脚本会优先判断场地(X号场)的时间是否与预设时间符合后预约，若不符合，则继续预约指定时间，若不成功，则随机
4. 不指定场地但指定时间，则脚本会按顺序预约指定时间的所有场地，若不成功，则进入随机预约

**Comment by X1a0He** [comment]
不过我很久没更新了，也懒得更新了，毕竟我不是广大的学生，能不能用随缘
