### ISSUE TITLE
关于代码运行速度的一点疑问

### ISSUE THREAD

**Issue by CangMingZhiYue** [X1a0He/GuangzhouUniversity#4]
您好博主，我今天自己抓包对照着看了一下整个代码的逻辑，想请问一下有没有把runInterfaceSuggest这一函数去掉的可能，代码`if (code === "TYCDYY_YYRQ") {
                        if (items[items.length - 1].enabled) {
                            codeId = items[items.length - 1].codeId;        //周几,
                            codeName = items[items.length - 1].codeName;    //日期
                            field.fieldYYRQ = codeId;
                            field.fieldZJ = codeId;
                            field.fieldYYRQ_Name = codeName;
                        }
                    }`中所获取到的日期都用本地时间代替，这样子可以直接减少post  'https://usc.gzhu.edu.cn/infoplus/interface/suggest'所耗费的时间

**Comment by CangMingZhiYue** [comment]
此外，如果使用python来实现整个自动化测试过程的话会不会运行速度更快一点

**Comment by X1a0He** [comment]
关于去掉你说的runInterfaceSuggest去掉部分代码的问题，我认为去不去掉无所谓，我写上只是怕官网那边会改成其他，假如说field.fieldYYRQ，field.fieldZJ和field.fieldYYRQ_Name不是现在的周几周几或者直接用本地能代替的，你还不是要再加上去，所以去不去掉无所谓

其次，你提到用python来实现整个过程会不会速度更快，我认为没什么区别也没必要神化py，毕竟实现方式不一样(不会py，没对比过)

最后，这个脚本我很久没维护了，可能还能用，也可能用不了，毕竟我也不是广大的学生，只是个写手罢了

**Comment by CangMingZhiYue** [comment]
> 关于去掉你说的runInterfaceSuggest去掉部分代码的问题，我认为去不去掉无所谓，我写上只是怕官网那边会改成其他，假如说field.fieldYYRQ，field.fieldZJ和field.fieldYYRQ_Name不是现在的周几周几或者直接用本地能代替的，你还不是要再加上去，所以去不去掉无所谓
> 
> 其次，你提到用python来实现整个过程会不会速度更快，我认为没什么区别也没必要神化py，毕竟实现方式不一样(不会py，没对比过)
> 
> 最后，这个脚本我很久没维护了，可能还能用，也可能用不了，毕竟我也不是广大的学生，只是个写手罢了

首先，感谢回答，这个脚本目前还是有作用的，我并不是神化python，只是在阅读代码时感觉js和python有一定程度上的相似性，而且我恰好是对nodejs不是太熟悉那一类的，经查询后发现因为某个谷歌”大聪明“把js玩出花来后人们才发现js的运行速度可以很快，故有此疑问
此外，我刚才尝试把runInterfaceSuggest去掉，改成了当日的本地时间，可以正常运行但是在下一步确定预约场地时出现”第一次预约 undefined undefined“文本，我猜测是如果不post  https://usc.gzhu.edu.cn/infoplus/interface/suggest 的话可能会导致下一步无法继续
最后，我还有一个问题，就是如果把“到达指定时间再开始运行”思路 改成”一直发请求直到返回正确“ 是否可行

**Comment by X1a0He** [comment]
你可以稍微看一下这次的commit
[#bc9608](https://github.com/X1a0He/GuangzhouUniversity/commit/bc9608d3b9f7ca5b26d8bdbbec4ed829321e44e2)

并且你提到的本地生成在这里也得到了实现，但是我还是认为本地生成迟早会影响最终结果
[2023-09-14 19:55 Update](https://github.com/X1a0He/GuangzhouUniversity#log)
