### ISSUE TITLE
一些感想

### ISSUE THREAD

**Issue by CangMingZhiYue** [X1a0He/GuangzhouUniversity#5]
在开头还是得感谢一下老哥，老哥的coding速率十分之高，明天我试用一下看有没有什么问题(因为今天已经预约满了，或者等会用乒乓球试一下)，我今天试着用python去复现这一程序，由于个人水平不足，目前才复现到”runInterfaceRender“这一函数，正在苦恼`                        let {
                            fieldSF,
                            fieldLSH,
                            fieldSQSJ,
                            fieldXM,
                            fieldXM_Name,
                            fieldXH,
                            fieldXY,
                            fieldXY_Name
                        } = info;
                        fieldChanging({
                            fieldSF,
                            fieldLSH,
                            fieldSQSJ,
                            fieldXM,
                            fieldXM_Name,
                            fieldXH,
                            fieldXY,
                            fieldXY_Name
                        });`
这一段的数组处理，我今天再详细看了一遍抓的包，codeId和codeName应该是不会出大问题，但是老哥的担心确实不无道理，万一哪天修改了不是日期了呢，不过那时候整段程序估计也需要大改了哈哈哈哈（所以再拿Python写一个也是有备无患）。
此外，最近可能是人多也可能是其他别的问题，在doAction确认预约时经常会出现抢不过的情况，也许都是科技兴国吧哈哈哈

**Comment by X1a0He** [comment]
并不需要大改，我只是将从官网获取日期和周几的函数暂时注释掉而已，后期还是能用的

抢不过的情况不能怪脚本，只能说这东西，网络和运气各占一半

你所苦恼的东西是JS的解构语法，python不知道有没有，我也不会，我只能解释给你听，具体意思如下

```js
let { fieldSF, fieldLSH, fieldSQSJ, fieldXM, fieldXM_Name, fieldXH, fieldXY, fieldXY_Name } = info
fieldChanging({ fieldSF, fieldLSH, fieldSQSJ, fieldXM, fieldXM_Name, fieldXH, fieldXY, fieldXY_Name })
```

由于info是一个对象，对象里有键值对，也就是相应的"key": value，第一行的写法就是将info里对应值取出来并赋值
而fieldChanging只是一个我懒得慢慢去一行一行赋值，索性一下子赋值的函数罢了，传入的就是对象，而函数具体实现也是取的对应值，python的话，你可以一个一个赋值，一样的效果

**Comment by CangMingZhiYue** [comment]
> 并不需要大改，我只是将从官网获取日期和周几的函数暂时注释掉而已，后期还是能用的
> 
> 抢不过的情况不能怪脚本，只能说这东西，网络和运气各占一半
> 
> 你所苦恼的东西是JS的解构语法，python不知道有没有，我也不会，我只能解释给你听，具体意思如下
> 
> ```js
> let { fieldSF, fieldLSH, fieldSQSJ, fieldXM, fieldXM_Name, fieldXH, fieldXY, fieldXY_Name } = info
> fieldChanging({ fieldSF, fieldLSH, fieldSQSJ, fieldXM, fieldXM_Name, fieldXH, fieldXY, fieldXY_Name })
> ```
> 
> 由于info是一个对象，对象里有键值对，也就是相应的"key": value，第一行的写法就是将info里对应值取出来并赋值 而fieldChanging只是一个我懒得慢慢去一行一行赋值，索性一下子赋值的函数罢了，传入的就是对象，而函数具体实现也是取的对应值，python的话，你可以一个一个赋值，一样的效果

感谢老哥，我苦恼的正是python如何简单快速地去实现这个问题，我刚刚用乒乓球测试了一下脚本，是可以正常运行的，我自己画蛇添足更改了主函数的一步` while(!now) await runInterfaceRender();`，目的是让他在没到12:30:00时一直运行runInterfaceRender()函数，虽然这样子可能导致整个循环跳不出来卡住，但是我一般是放在云服务器上跑的，大不了重启云服务器就完事了哈哈哈哈

**Comment by CangMingZhiYue** [comment]
我在python中的想法是设置一个ddl（在老哥写的脚本上也是如此），如果超过这个ddl的话会把now 设置为 true 而跳出循环(按照广大抢场的剧烈程度，基本上12:30:05就没场了，所以这个思路我个人觉得行得通)，这个now我把它放在 runInterfaceRender()函数中 notNow = false 下一行的位置

**Comment by X1a0He** [comment]
没到12:30是不会放预约链接的，所以这就是为什么我做不到一直请求直到开放预约为止

至于放在哪里无所谓，毕竟差不了多少时间，程序判断的时间可以忽略的

**Comment by CangMingZhiYue** [comment]
> 没到12:30是不会放预约链接的，所以这就是为什么我做不到一直请求直到开放预约为止
> 
> 至于放在哪里无所谓，毕竟差不了多少时间，程序判断的时间可以忽略的

首先，感谢老哥答疑，我担心的不是程序判断的时间，而是放在这个位置会不会报错，毕竟我在nodejs上的造诣很低哈哈哈哈哈哈哈
我想加上 “一直请求直到开放预约”这个功能是出于我自身使用的体验，在实际使用过程中，可能会出现“本地时间”和“服务器时间”不对应的情况，比如本地慢0.5秒或者快一点，从而会导致有一个时间差，即使每天都进行一次时间同步也无法确保时间会一模一样，程序判断的时间可以忽略不计，但是这个时间差很有可能就影响到了抢场结果。
我一开始的想法是从服务器获取时间从而同步，但是经过网上百度之后发现实现起来非常麻烦且很容易出问题，所以就诞生了”一直请求“这个想法，如果是一直请求的话就不用担心这个时间差了，可以在开放预约的第一时间立即进入

**Comment by X1a0He** [comment]
一直请求有一个弊端，就是要等返回值才能进行下一步，假如说网络卡了，刚好预约开始了，那不就卡在等返回值那一步了

再说了，本地时间与服务器时间不对应的问题就像你说的永远都无法解决，从服务器同步时间还是会绕回脚本会被网络因素影响的问题，所以很多时候不用担心太多，网络+运气就足够了
