### ISSUE TITLE
预约报错

### ISSUE THREAD

**Issue by William-ZZh** [X1a0He/GuangzhouUniversity#6]
你好，我把yuyue.js文件替换成你最新修改的版本了，然后在预约的过程中出现以下的错误，错误显示为：（Error: Unexpected token < in JSON at position 0. Please check your data.
Error: Unexpected token < in JSON at position 0. Please check your data.
❌ 广州大学羽毛球场地预约, 失败! 原因: TypeError: Cannot read properties of undefined (reading '')!）
我需要做哪些修改才能正常预约呢

**Comment by X1a0He** [comment]
刚才看了一下，应该是你们学校准备进行改版，先预热测试一下，导致获取预约链接需要加密参数才能获取，现在已经被撤销了，不知道会不会再次加密

**Comment by X1a0He** [comment]
现在是正常的了

**Comment by William-ZZh** [comment]
好的，非常感谢！！！ 我昨天也是同一个原因，然后预约失败，今天也是。我明天再继续试一试，很感谢你提供了这个代码！！！

**Comment by William-ZZh** [comment]
> 刚才看了一下，应该是你们学校准备进行改版，先预热测试一下，导致获取预约链接需要加密参数才能获取，现在已经被撤销了，不知道会不会再次加密

你好哥，我今天中午再试了一下，没有出现前几天的错误了，但是又出现了一个新的错误：（ "{\"errno\":22001,\"ecode\":\"EVENT_CANCELLED\",\"error\":\"中午12点半后才可预约。\",\"entities\":[]}"
[2023-09-24 12:30:00] 预约执行完毕，预约耗时 0.237 秒），报错之后我重新输入node yuyue又能正确运行了，然后有抢到场了。哥，这个前面的错误可以怎么修改吗？

**Comment by qrwedsdf** [comment]
> > 刚才看了一下，应该是你们学校准备进行改版，先预热测试一下，导致获取预约链接需要加密参数才能获取，现在已经被撤销了，不知道会不会再次加密
> 
> 你好哥，我今天中午再试了一下，没有出现前几天的错误了，但是又出现了一个新的错误：（ "{"errno":22001,"ecode":"EVENT_CANCELLED","error":"中午12点半后才可预约。","entities":[]}" [2023-09-24 12:30:00] 预约执行完毕，预约耗时 0.237 秒），报错之后我重新输入node yuyue又能正确运行了，然后有抢到场了。哥，这个前面的错误可以怎么修改吗？

你好，我今天也是这样，请问现在解决了吗，怎么修改的啊
